# Generated by Django 5.1.2 on 2024-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('contador', 'Contador')], default='admin', max_length=20),
        ),
    ]
