# Generated by Django 5.1.2 on 2024-11-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_proveedor_estado_proveedor_ruc_alter_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='FacturaCliente',
        ),
        migrations.DeleteModel(
            name='FacturaProveedor',
        ),
    ]
