# Generated by Django 5.1.2 on 2024-11-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
