# Generated by Django 5.1.2 on 2024-11-27 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente relacionado'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor', verbose_name='Proveedor relacionado'),
        ),
    ]
